project_name: newscope

before:
  hooks:
    - go mod download
    - go mod vendor

builds:
  - id: newscope
    binary: newscope
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}-{{.CommitDate}}-{{.ShortCommit}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: packages
    package_name: newscope
    homepage: https://github.com/umputun/newscope
    description: AI-powered RSS feed curator
    maintainer: Umputun <umputun@gmail.com>
    license: MIT
    vendor: Umputun
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/newscope/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/newscope/README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: umputun
    name: newscope
  draft: false
  prerelease: auto