app:
  name: "Newscope"
  version: "2.0.0"
  
server:
  listen: ":8080"
  timeout: "30s"

database:
  dsn: "./var/newscope.db"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 3600

schedule:
  update_interval: 30    # minutes
  max_workers: 20

llm:
  # OpenAI-compatible endpoint (OpenAI, Ollama, etc)
  #endpoint: "http://localhost:11434/v1"  # Ollama example
  endpoint: "https://api.openai.com/v1" # OpenAI example
  
  api_key: "${OPENAI_API_KEY}"  # From environment
  model: "gpt-4o-mini"                # or "gpt-4o-mini"
  temperature: 0.3               # Lower = more consistent
  max_tokens: 2000               # Increased for summaries
  timeout: "30s"
  
  # Optional: Custom system prompt for classification
  # system_prompt: |
  #   You are a tech news curator. Rate articles from 0-10 based on:
  #   - Relevance to software development and technology
  #   - Innovation and emerging technologies
  #   - Practical applications and tutorials
  #   
  #   Respond with JSON array containing for each article:
  #   {
  #     "guid": "article GUID",
  #     "score": 0-10,
  #     "explanation": "brief reason (max 100 chars)",
  #     "topics": ["topic1", "topic2", "topic3"]
  #   }
  
  classification:
    score_threshold: 5.0       # Minimum score to include
    feedback_examples: 10      # Recent examples to include
    use_json_mode: true        # Use JSON mode for classification
    preferred_topics:          # Topics that increase article scores based on Radio-T content
      - "golang"
      - "rust" 
      - "ai"
      - "machine learning"
      - "programming"
      - "software development"
      - "open source"
      - "github"
      - "docker"
      - "typescript"
      - "coding"
      - "tech industry"
      - "claude"
      - "openai"
      - "anthropic"
      - "llm"
      - "coding assistants"
      - "development tools"
      - "software engineering"
    avoided_topics:            # Topics that decrease article scores
      - "sports"
      - "politics"
      - "celebrity"
      - "entertainment"
      - "fashion"
      - "lifestyle"
    
    # Optional: Custom prompts for preference summary generation
    # prompts:
    #   generate_summary: |
    #     Analyze the user's feedback history and create a preference profile.
    #     Focus on:
    #     - Technical depth preferences (beginner vs advanced)
    #     - Content types (tutorials, news, opinion pieces)
    #     - Specific technologies and domains of interest
    #     - Writing style preferences
    #     Limit to 200-300 words.
    #   
    #   update_summary: |
    #     Refine the existing preference profile based on new feedback.
    #     Maintain previous insights while incorporating new patterns.
    #     Note any shifts in interests or preferences.
    #     Keep within 200-300 words.

extraction:
  enabled: true
  timeout: "30s"
  max_concurrent: 5
  rate_limit: "1s"
  user_agent: "Newscope/2.0"
  min_text_length: 100
  include_images: false
  include_links: false

