// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/newscope/pkg/feed/types"
)

// FetcherMock is a mock implementation of feed.Fetcher.
//
//	func TestSomethingThatUsesFetcher(t *testing.T) {
//
//		// make and configure a mocked feed.Fetcher
//		mockedFetcher := &FetcherMock{
//			FetchFunc: func(ctx context.Context, feedURL string, feedName string) ([]types.FeedItem, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedFetcher in code that requires feed.Fetcher
//		// and then make assertions.
//
//	}
type FetcherMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, feedURL string, feedName string) ([]types.FeedItem, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FeedURL is the feedURL argument value.
			FeedURL string
			// FeedName is the feedName argument value.
			FeedName string
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *FetcherMock) Fetch(ctx context.Context, feedURL string, feedName string) ([]types.FeedItem, error) {
	if mock.FetchFunc == nil {
		panic("FetcherMock.FetchFunc: method is nil but Fetcher.Fetch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FeedURL  string
		FeedName string
	}{
		Ctx:      ctx,
		FeedURL:  feedURL,
		FeedName: feedName,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, feedURL, feedName)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedFetcher.FetchCalls())
func (mock *FetcherMock) FetchCalls() []struct {
	Ctx      context.Context
	FeedURL  string
	FeedName string
} {
	var calls []struct {
		Ctx      context.Context
		FeedURL  string
		FeedName string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
