// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"
)

// ConfigProviderMock is a mock implementation of server.ConfigProvider.
//
//	func TestSomethingThatUsesConfigProvider(t *testing.T) {
//
//		// make and configure a mocked server.ConfigProvider
//		mockedConfigProvider := &ConfigProviderMock{
//			GetServerConfigFunc: func() (string, time.Duration) {
//				panic("mock out the GetServerConfig method")
//			},
//		}
//
//		// use mockedConfigProvider in code that requires server.ConfigProvider
//		// and then make assertions.
//
//	}
type ConfigProviderMock struct {
	// GetServerConfigFunc mocks the GetServerConfig method.
	GetServerConfigFunc func() (string, time.Duration)

	// calls tracks calls to the methods.
	calls struct {
		// GetServerConfig holds details about calls to the GetServerConfig method.
		GetServerConfig []struct {
		}
	}
	lockGetServerConfig sync.RWMutex
}

// GetServerConfig calls GetServerConfigFunc.
func (mock *ConfigProviderMock) GetServerConfig() (string, time.Duration) {
	if mock.GetServerConfigFunc == nil {
		panic("ConfigProviderMock.GetServerConfigFunc: method is nil but ConfigProvider.GetServerConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetServerConfig.Lock()
	mock.calls.GetServerConfig = append(mock.calls.GetServerConfig, callInfo)
	mock.lockGetServerConfig.Unlock()
	return mock.GetServerConfigFunc()
}

// GetServerConfigCalls gets all the calls that were made to GetServerConfig.
// Check the length with:
//
//	len(mockedConfigProvider.GetServerConfigCalls())
func (mock *ConfigProviderMock) GetServerConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetServerConfig.RLock()
	calls = mock.calls.GetServerConfig
	mock.lockGetServerConfig.RUnlock()
	return calls
}
