// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"

	"github.com/umputun/newscope/pkg/config"
)

// ConfigProviderMock is a mock implementation of server.ConfigProvider.
//
//	func TestSomethingThatUsesConfigProvider(t *testing.T) {
//
//		// make and configure a mocked server.ConfigProvider
//		mockedConfigProvider := &ConfigProviderMock{
//			GetFullConfigFunc: func() *config.Config {
//				panic("mock out the GetFullConfig method")
//			},
//			GetServerConfigFunc: func() (string, time.Duration) {
//				panic("mock out the GetServerConfig method")
//			},
//		}
//
//		// use mockedConfigProvider in code that requires server.ConfigProvider
//		// and then make assertions.
//
//	}
type ConfigProviderMock struct {
	// GetFullConfigFunc mocks the GetFullConfig method.
	GetFullConfigFunc func() *config.Config

	// GetServerConfigFunc mocks the GetServerConfig method.
	GetServerConfigFunc func() (string, time.Duration)

	// calls tracks calls to the methods.
	calls struct {
		// GetFullConfig holds details about calls to the GetFullConfig method.
		GetFullConfig []struct {
		}
		// GetServerConfig holds details about calls to the GetServerConfig method.
		GetServerConfig []struct {
		}
	}
	lockGetFullConfig   sync.RWMutex
	lockGetServerConfig sync.RWMutex
}

// GetFullConfig calls GetFullConfigFunc.
func (mock *ConfigProviderMock) GetFullConfig() *config.Config {
	if mock.GetFullConfigFunc == nil {
		panic("ConfigProviderMock.GetFullConfigFunc: method is nil but ConfigProvider.GetFullConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetFullConfig.Lock()
	mock.calls.GetFullConfig = append(mock.calls.GetFullConfig, callInfo)
	mock.lockGetFullConfig.Unlock()
	return mock.GetFullConfigFunc()
}

// GetFullConfigCalls gets all the calls that were made to GetFullConfig.
// Check the length with:
//
//	len(mockedConfigProvider.GetFullConfigCalls())
func (mock *ConfigProviderMock) GetFullConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetFullConfig.RLock()
	calls = mock.calls.GetFullConfig
	mock.lockGetFullConfig.RUnlock()
	return calls
}

// GetServerConfig calls GetServerConfigFunc.
func (mock *ConfigProviderMock) GetServerConfig() (string, time.Duration) {
	if mock.GetServerConfigFunc == nil {
		panic("ConfigProviderMock.GetServerConfigFunc: method is nil but ConfigProvider.GetServerConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetServerConfig.Lock()
	mock.calls.GetServerConfig = append(mock.calls.GetServerConfig, callInfo)
	mock.lockGetServerConfig.Unlock()
	return mock.GetServerConfigFunc()
}

// GetServerConfigCalls gets all the calls that were made to GetServerConfig.
// Check the length with:
//
//	len(mockedConfigProvider.GetServerConfigCalls())
func (mock *ConfigProviderMock) GetServerConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetServerConfig.RLock()
	calls = mock.calls.GetServerConfig
	mock.lockGetServerConfig.RUnlock()
	return calls
}
